server {
    listen 8080;

    location /downstream/quotes/ {
        default_type application/json;
        return 200 '{"id": "STATIC", "price": 100.0, "degraded": false, "source": "live"}';
    }
}
