#!/usr/bin/env python3
"""Render the §4 master inventory table from _catalog-inventory.yml.

Usage:
    python3 scripts/render-catalog-table.py \
        --yaml governance/standards/_catalog-inventory.yml \
        --markdown governance/standards/enterprise-architecture-catalog.md \
        --section 4

Replaces the content between `## 4. Master Inventory Table` and the next `## ` header.
"""
import argparse
import re
import sys
from pathlib import Path

import yaml


def render_table(rows: list[dict]) -> str:
    out = [
        "## 4. Master Inventory Table",
        "",
        "> **Source of truth**: `_catalog-inventory.yml`. This table is regenerated by `scripts/render-catalog-table.py`. Do not hand-edit.",
        "",
        "| ID | Title | Category | Status | Spine | Owner | Path | Tiers | Compliance | Last Reviewed | Wave | Notes |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda x: x["id"]):
        cr = r.get("compliance_refs", {}) or {}
        compliance = "; ".join(
            ref
            for ring in ("ring0", "ring1", "ring2")
            for ref in (cr.get(ring) or [])
        ) or "—"
        tiers = ", ".join(r.get("tiers", []) or []) or "—"
        owner = "@" + r.get("owner", "tbd")
        spine = r.get("spine_or_radii", "radii")
        notes = (r.get("notes", "") or "").replace("|", "\\|")
        out.append(
            f"| {r['id']} | {r['title']} | {r['category']} | {r['status']} | {spine} | "
            f"{owner} | `{r['path']}` | {tiers} | {compliance} | "
            f"{r.get('last_reviewed', '—')} | {r.get('target_wave', '—')} | {notes} |"
        )
    return "\n".join(out) + "\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--yaml", required=True)
    p.add_argument("--markdown", required=True)
    p.add_argument("--section", type=int, default=4)
    args = p.parse_args()

    data = yaml.safe_load(Path(args.yaml).read_text())
    rendered = render_table(data["rows"])

    md = Path(args.markdown).read_text()
    pattern = re.compile(
        rf"^## {args.section}\..*?(?=^## )", re.DOTALL | re.MULTILINE
    )
    if not pattern.search(md):
        sys.exit(f"Section {args.section} not found in {args.markdown}")
    new_md = pattern.sub(rendered + "\n", md)
    Path(args.markdown).write_text(new_md)

    by_status: dict[str, int] = {}
    for r in data["rows"]:
        by_status[r["status"]] = by_status.get(r["status"], 0) + 1
    summary = ", ".join(f"{k}={v}" for k, v in sorted(by_status.items()))
    print(f"Rendered {len(data['rows'])} rows into §{args.section} ({summary})")


if __name__ == "__main__":
    main()
